int32 idx
---
int16 result
int16 SUCCESS=0
int16 FAILURE=1
int16 MOTION_FAILED=2
int16 MISSING_KEYFRAME=3
int16 CONTACT_DETECTION_NOT_RUNNING=4
int16 FOLDING_CONTROLLER_NOT_RUNNING=5
int16 FAILED_CONTACT=6

---